create table speciality (
	job_id INT,
	name VARCHAR(50)
);
insert into speciality (job_id, name) values (1, 'Geological Engineer');
insert into speciality (job_id, name) values (2, 'Mechanical Systems Engineer');
insert into speciality (job_id, name) values (3, 'Recruiting Manager');
insert into speciality (job_id, name) values (4, 'Paralegal');
insert into speciality (job_id, name) values (5, 'Recruiter');
insert into speciality (job_id, name) values (6, 'Mechanical Systems Engineer');
insert into speciality (job_id, name) values (7, 'Professor');
insert into speciality (job_id, name) values (8, 'Financial Analyst');
insert into speciality (job_id, name) values (9, 'Nuclear Power Engineer');
insert into speciality (job_id, name) values (10, 'Automation Specialist II');
insert into speciality (job_id, name) values (11, 'Administrative Officer');
insert into speciality (job_id, name) values (12, 'Systems Administrator II');
insert into speciality (job_id, name) values (13, 'Chief Design Engineer');
insert into speciality (job_id, name) values (14, 'Chemical Engineer');
insert into speciality (job_id, name) values (15, 'Software Consultant');
insert into speciality (job_id, name) values (16, 'Actuary');
insert into speciality (job_id, name) values (17, 'Human Resources Manager');
insert into speciality (job_id, name) values (18, 'Biostatistician I');
insert into speciality (job_id, name) values (19, 'Budget/Accounting Analyst IV');
insert into speciality (job_id, name) values (20, 'Marketing Assistant');
insert into speciality (job_id, name) values (21, 'Budget/Accounting Analyst IV');
insert into speciality (job_id, name) values (22, 'Cost Accountant');
insert into speciality (job_id, name) values (23, 'Recruiting Manager');
insert into speciality (job_id, name) values (24, 'Director of Sales');
insert into speciality (job_id, name) values (25, 'Systems Administrator II');
insert into speciality (job_id, name) values (26, 'Software Test Engineer II');
insert into speciality (job_id, name) values (27, 'Financial Analyst');
insert into speciality (job_id, name) values (28, 'Internal Auditor');
insert into speciality (job_id, name) values (29, 'Nurse');
insert into speciality (job_id, name) values (30, 'Help Desk Technician');
insert into speciality (job_id, name) values (31, 'Environmental Specialist');
insert into speciality (job_id, name) values (32, 'Nuclear Power Engineer');
insert into speciality (job_id, name) values (33, 'Marketing Manager');
insert into speciality (job_id, name) values (34, 'Software Consultant');
insert into speciality (job_id, name) values (35, 'Environmental Specialist');
insert into speciality (job_id, name) values (36, 'Account Coordinator');
insert into speciality (job_id, name) values (37, 'Staff Scientist');
insert into speciality (job_id, name) values (38, 'Geologist I');
insert into speciality (job_id, name) values (39, 'Programmer Analyst III');
insert into speciality (job_id, name) values (40, 'Help Desk Operator');
insert into speciality (job_id, name) values (41, 'Marketing Assistant');
insert into speciality (job_id, name) values (42, 'Programmer III');
insert into speciality (job_id, name) values (43, 'Staff Accountant I');
insert into speciality (job_id, name) values (44, 'Electrical Engineer');
insert into speciality (job_id, name) values (45, 'Social Worker');
insert into speciality (job_id, name) values (46, 'Safety Technician I');
insert into speciality (job_id, name) values (47, 'Senior Editor');
insert into speciality (job_id, name) values (48, 'Software Consultant');
insert into speciality (job_id, name) values (49, 'Marketing Assistant');
insert into speciality (job_id, name) values (50, 'Research Assistant I');
